package: d2u_jobs
version: '2.0.0'
author: Tobias Krais

page:
    title: 'translate:d2u_jobs'
    perm: 'd2u_jobs[]'
    icon: rex-icon fa-users

requires:
    redaxo: '>=5.16.0'
    packages:
        d2u_helper: '>=1.14.0'
        jobs: '>=1.0.0'
        sprog: '>=1.0.0'
        url: '>=2.0'
        yrewrite: '>=2.0.1'
    php: '>=8.0'

installer_ignore:
    - .github