package: d2u_jobs
version: '1.2.2'
author: Tobias Krais

page:
    title: 'translate:d2u_jobs'
    perm: 'd2u_jobs[]'
    icon: rex-icon fa-users
    subpages:
        jobs: { title: 'translate:d2u_jobs_jobs', icon: rex-icon fa-users }
        category: { title: 'translate:d2u_helper_category', icon: rex-icon rex-icon-open-category }
        contact: { title: 'translate:d2u_jobs_contacts', icon: rex-icon rex-icon-user, perm: 'd2u_jobs[edit_data]' }
        setup: { title: 'translate:d2u_helper_setup', icon: rex-icon rex-icon-install, itemclass: pull-right, perm: 'd2u_jobs[settings]' }
        settings: { title: 'translate:d2u_helper_settings', icon: rex-icon rex-icon-system, itemclass: pull-right, perm: 'd2u_jobs[settings]' }

requires:
    redaxo: '>=5.10.0'
    packages:
        d2u_helper: '>=1.8.8'
        sprog: '>=1.0.0'
        url: '>=2.0'
        yrewrite: '>=2.0.1'